### ISSUE TITLE
Building with new pipeline QL-1.23 and boost_1_77_0 - Transformation Error

### ISSUE THREAD

**Issue by gwd666** [klausspanderen/RHestonSLV#1]
Hello and thanks for this nice package 

I tried to build RHestonSLV for R-4.0.5 (thereby also relying mostly on the new Rtools40 toolchain) but then ran into two errors 

OS:Windows 10 
R.version: R-4.0.5 using Rtools 4 w MinGW 64-Bit for building 
boost 1.77.0
QuantLib 1.23

1. First error that popped up ... I was able to fix - since that was just an include that needed some updating because of `localvolrndcalculator`  moving from `experimtental/finitedifferences` to `methods/finitedifferences/utilities` - for which I could offer a pull request (if you would like to include it?)

BUT on the second one I am stuck, since I am not familiar enough with the Transformations between objects being poossible and/or going on in QuantLib or your code, which maybe (also) got "broken" by some updates in QL [or boost]? 
2. This 2nd error during binary package building looks like:  
```
hestonslvmodule.cpp:458:5: error: cannot convert 'const QuantLib::FdmSquareRootFwdOp::TransformationType' to 'const QuantLib::FdmHestonGreensFct::Algorithm' in initialization
hestonslvmodule.cpp:458:5: error: cannot convert 'const QuantLib::FdmSchemeDesc' to 'const QuantLib::FdmSquareRootFwdOp::TransformationType' in initialization
hestonslvmodule.cpp:458:5: error: could not convert '<brace-enclosed initializer list>()' from '<brace-enclosed initializer list>' to 'const QuantLib::FdmSchemeDesc'
make: *** [C:/PROGRA~1/R/R-40~1.5/etc/i386/Makeconf:229: hestonslvmodule.o] Error 1
ERROR: compilation failed for package 'RHestonSLV'
```
Any hints where I should potentially adapt source or look further into detail ... *warning you -> I am a bit / quite rusty on my C++

Thanks 
GWD

**Comment by gwd999** [comment]
Same issue/error when building on Ubuntu 20.04  with boost-1_71 installed via `apt` in standard location [`/usr/include/boost`] 
and using QuantLib-1.17 
QuantLib was build w/o any problems and seems to work - at least the examples are working all right. But when trying to build RHestonSLV 

```
hestonslvmodule.cpp:456:7: warning: narrowing conversion of ‘(QuantLib::FdmHestonGreensFct::Algorithm)greensAlgorithm’ from ‘QuantLib::FdmHestonGreensFct::Algorithm’ to ‘QuantLib::Real’ {aka ‘double’} [-Wnarrowing]
  456 |       greensAlgorithm,
      |       ^~~~~~~~~~~~~~~
hestonslvmodule.cpp:457:7: error: cannot convert ‘const QuantLib::FdmSquareRootFwdOp::TransformationType’ to ‘const QuantLib::FdmHestonGreensFct::Algorithm’ in initialization
  457 |       transformationType,
      |       ^~~~~~~~~~~~~~~~~~
      |       |
      |       const QuantLib::FdmSquareRootFwdOp::TransformationType
hestonslvmodule.cpp:458:7: error: cannot convert ‘const QuantLib::FdmSchemeDesc’ to ‘const QuantLib::FdmSquareRootFwdOp::TransformationType’ in initialization
  458 |       schemeDesc
      |       ^~~~~~~~~~
      |       |
      |       const QuantLib::FdmSchemeDesc
hestonslvmodule.cpp:459:5: error: could not convert ‘<brace-enclosed initializer list>()’ from ‘<brace-enclosed initializer list>’ to ‘const QuantLib::FdmSchemeDesc’
  459 |     };
      |     ^
      |     |
      |     <brace-enclosed initializer list>
make: *** [/usr/local/lib/R/etc/Makeconf:181: hestonslvmodule.o] Error 1
ERROR: compilation failed for package ‘RHestonSLV’
```

**Comment by klausspanderen** [comment]
Hi,

thanks for the hint, the package was a bit outdated. I've updated the package to work with QuantLib 1.12 or higher. Works and tested on Ubuntu 20.04. I do not have a working R 4.0 installation, hence I''d be interest to hear about any issues.

best regards
Klaus

**Comment by gwd999** [comment]
@klausspanderen 
I will test it for Ubuntu + R-4 ... and keep you updated, respectively get in touch here (potentially new ticket) if something pops up; curious how you fixed those `brace initializers`  ... gonna fetch new code right away
Thanks!

**Comment by gwd666** [comment]
> I do not have a working R 4.0 installation, hence I''d be interest to hear about any issues.

Will put that (ie R-4 on Windows testing) on my agenda ...      
if something else breaks (or is broken) I will open a separate/new  ticket
